### ISSUE TITLE
python3 incompatibility

### ISSUE THREAD

**Issue by damienjadeduff** [RunestoneInteractive/webfundamentals#1]
When serving webfundamentals via pythoninteractive.org or locally, many of the examples are Python 2 style but activecode I think is expecting Python 3 by default.

See http://interactivepython.org/runestone/static/webfundamentals/CGI/basiccgi.html

The following code...

```
#!/usr/bin/python

print "Content-type: text/html\n"
print ""
print ""
print "Hello %s" % "World"
print ""
print ""
```

...leads to...

```
ParseError: bad input on line 3
```

Editing `pavement.py` to add...

```
        'python3': 'false',
```

...fixes it locally, but the online hosted default textbook still has the problem (see the above URL).

**Comment by bnmnetp** [comment]
Thanks for pointing that out.  I need to rebuild the online book today with a bunch of other changes to the Part I.  I'll change the python3 flag to false for now.  Probably false should be the default for this project for now.

Please understand that Part II is in very rough shape.  I have used Part I, in a seven week course for non-majors and majors four times now, but Part II needs a lot of work before next Spring.

PS -- I visited Istanbul twice this past year.  Enjoyed our time there very much!

**Comment by damienjadeduff** [comment]
Thanks Brad, yes reading on in the book this becomes clear. In our course we hide most of the details from our students anyway and serve via PythonAnywhere WSGI so it probably would not make sense to use the second part of this textbook (too advanced for us; goes via CGI to start with). It's nice that the javascript part is not a dependency though.

Please drop us a line if you are ever in Istanbul again. 

And thank you for this fantastic resource.

**Comment by bnmnetp** [comment]
fixed
