### ISSUE TITLE
Typo Link

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/webfundamentals#4]
Error reported in course CS4131Fall2019 on page intro by user ungxx028 ungxx028@umn.edu
The resructuredText hyperlink leads to the wrong location. In chrome, clicking on the hyperlink directs us to the following: https://http//sphinx-doc.org/rest.html

The rest of the hyperlinks on the page are functional.

**Comment by bnmnetp** [comment]
Thanks -- Fixed
