### ISSUE TITLE
wrong child listed in example explanation

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/webfundamentals#5]
Error reported in course CS4131Fall2019 on page intro by user ungxx028 ungxx028@umn.edu
Passage at the bottom says:
The html tag has two children, the head and the body. The head has one child, which is the head tag. The html tag is the parent of the head tag.

Should read:
The html tag has two children, the head and the body. The head has one child, which is the title tag. The html tag is the parent of the head tag.

**Comment by bnmnetp** [comment]
Thanks -- Fixed
