### ISSUE TITLE
Improper spelling

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/webfundamentals#6]
Error reported in course CS4131Fall2019 on page https://runestone.academy/runestone/books/published/webfundamentals/Javascript/events.html by user JaredErlien erlie003@umn.edu
Right below activity 2 is this sentence -
"Typing return or clicking with the mouse is still not as godd as we could do. "

Good is mispelled.

**Comment by bnmnetp** [comment]
Thanks.
