### ISSUE TITLE
Seemingly wrong statement in exercise

### ISSUE THREAD

**Issue by mcnoat** [RunestoneInteractive/webfundamentals#7]
I'm confused by an exercise in _sources/Javascript/objects.rst

The basis for the exercise is this code here:
```<html>
   <body>
      <h1>Hello World!!</h1>
      <button onclick="changeThisPageFunc();">Click Me!</button>
      <main>
         <h1>Hello Main</h2>
         <p>The quick brown fox jumped over the lazy dog.</p>
      </main>
      <script type="text/javascript">
         changeThisPageFunc = function() {
            var myMain;
            document.body.style.backgroundColor = "lightblue";
            myMain = document.querySelector('main');
            myMain.innerHTML = "<h3>Where have all the flowers gone?<h3>";
            myMain.style.height = "50px";
            myMain.style.width = "50%";
            myMain.style.backgroundColor = "lightgreen";
         }
      </script>
   </body>
</html>
```
At the bottom of the page it says "Change the HTML so that main has an id of "a". Also add a second main tag that contains an h1."
As far as I understand this, I have to modify the code like this:

```
...
      <button onclick="changeThisPageFunc();">Click Me!</button>
      <main id="a">
...
      </main>
      <script type="text/javascript">
         changeThisPageFunc = function() {
...
         }
      </script>
      <main>
         <h1>Another main</h1>
      </main>
   </body>
</html>
```
When I run the code, the new h1 is being displayed. However, in the exercise it says "The initial view of your page should not change." This is obviously not the case. Am I doing something wrong?

**Comment by bnmnetp** [comment]
Yes, the point of the exercise is that now the querySelector returns 2 things.  So you really should be using getElementById to keep the initial view of the page the same.
